version: "3.7"
services:
  db:
    image: postgres:15
#    restart: always
    container_name: db_app
    env_file:
      - .env-non-dev

  app:
    build:
      context: .
#    restart: always
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: sh -c "alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure




